### ISSUE TITLE
Analysis or dissection of the packet, do you have a way out?

### ISSUE THREAD

**Issue by sabhishepalc** [napatech/dpdk#1]
We can store the pcap with pdump, if we are in a need of dissection, is there any good way to do it?

**Comment by mlilja01** [comment]
I need a bit more context here :)
pdump is a standard DPDK feature that needs to be enabled. It will create a copy of the packet on ingress and egress to a file.

With our own NICs we actually have a way to monitor/dump to pcap more effectively without DPDK pdump.

**Comment by bkuhre** [comment]
Closed due to inactivity.
