### ISSUE TITLE
Deadlock when rte_flow_create fails

### ISSUE THREAD

**Issue by breyntjens** [napatech/dpdk#2]
When `rte_flow_create` fails due to an error in `DoNtpl`, the next DPDK call can hang due to a deadlock.
In my case I tried to clean up after the failed `rte_flow_create` by calling `rte_flow_flush`, which hangs indefinitely (waiting for a lock).

I believe the cause is a missing `NTACC_UNLOCK(&internals->configlock);` when an error occurs in `DoNtpl`:
https://github.com/napatech/dpdk/blob/3f97df18100553a6bd6f1250fedb1d67738a5c60/drivers/net/ntacc/rte_eth_ntacc.c#L2314-L2322

**Comment by bkuhre** [comment]
Yes this is an error. I will take a look at it. Thank you.

**Comment by bkuhre** [comment]
This has been corrected in the latest version.
