### ISSUE TITLE
Potential deadlock error due to the unrelased lock &sh->txpp.mutex

### ISSUE THREAD

**Issue by jenny-cheung** [napatech/dpdk#4]
Hi, developers, thank you for your checking. The lock &sh->txpp.mutex may be not released correctly the method returns at the `branch !sh->txpp.refcnt || --sh->txpp.refcnt` satisfies. The fix is to insert `pthread_mutex_lock(&sh->txpp.mutex);` before returning.

https://github.com/napatech/dpdk/blob/a384ad17c47b230f1d07577448a597a122222385/drivers/net/mlx5/mlx5_txpp.c#L951

https://github.com/napatech/dpdk/blob/a384ad17c47b230f1d07577448a597a122222385/drivers/net/mlx5/mlx5_txpp.c#L956

```
void
mlx5_txpp_stop(struct rte_eth_dev *dev)
{
	struct mlx5_priv *priv = dev->data->dev_private;
	struct mlx5_dev_ctx_shared *sh = priv->sh;
	int ret;

	if (!priv->txpp_en) {
		return;
	}
	priv->txpp_en = 0;
	ret = pthread_mutex_lock(&sh->txpp.mutex); // the lock
	MLX5_ASSERT(!ret);
	RTE_SET_USED(ret);
	MLX5_ASSERT(sh->txpp.refcnt);
	if (!sh->txpp.refcnt || --sh->txpp.refcnt)
		return;  // return without releasing
	
	mlx5_txpp_destroy(sh);
	ret = pthread_mutex_unlock(&sh->txpp.mutex);
	MLX5_ASSERT(!ret);
	RTE_SET_USED(ret);
}
```

**Comment by jenny-cheung** [comment]
Hi, developers @bkuhre 

Any comments would be highly appreciated. Thank you.

Best Regards,

**Comment by bkuhre** [comment]
This is an issue in the Melanox code. You should post the issue on the DPDK Homepage. This DPDK is a Napatech fork of the main DPDK. It is mainly for the Napatech PMD and adapters.

**Comment by jenny-cheung** [comment]
@bkuhre OK, I will also report it to Melanox code.
